local hop = require("hop")
hop.setup({ keys = "etovxqpdygfblzhckisuran" })

local opts = { noremap = true, silent = true }
local directions = require("hop.hint").HintDirection

vim.keymap.set("", "0f", function()
  hop.hint_patterns({ direction = directions.AFTER_CURSOR, current_line_only = false })
end, opts)
vim.keymap.set("", "0F", function()
  hop.hint_patterns({ direction = directions.BEFORE_CURSOR, current_line_only = false })
end, opts)
-- vim.keymap.set("", "t", function()
--   hop.hint_patterns({ direction = directions.AFTER_CURSOR, current_line_only = false, hint_offset = -1 })
-- end, opts)
-- vim.keymap.set("", "T", function()
--   hop.hint_patterns({ direction = directions.BEFORE_CURSOR, current_line_only = false, hint_offset = 1 })
-- end, opts)

vim.keymap.set("", "1f", function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false })
end, opts)
vim.keymap.set("", "1F", function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false })
end, opts)
-- vim.keymap.set("", "1t", function()
--   hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false, hint_offset = -1 })
-- end, opts)
-- vim.keymap.set("", "1T", function()
--   hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false, hint_offset = 1 })
-- end, opts)

vim.keymap.set("", "2f", function()
  hop.hint_char2({ direction = directions.AFTER_CURSOR, current_line_only = false })
end, opts)
vim.keymap.set("", "2F", function()
  hop.hint_char2({ direction = directions.BEFORE_CURSOR, current_line_only = false })
end, opts)
-- vim.keymap.set("", "2t", function()
--   hop.hint_char2({ direction = directions.AFTER_CURSOR, current_line_only = false, hint_offset = -1 })
-- end, opts)
-- vim.keymap.set("", "2T", function()
--   hop.hint_char2({ direction = directions.BEFORE_CURSOR, current_line_only = false, hint_offset = 1 })
-- end, opts)

vim.keymap.set("", "3f", function()
  hop.hint_lines_skip_whitespace({ direction = directions.AFTER_CURSOR })
end, opts)
vim.keymap.set("", "3F", function()
  hop.hint_lines_skip_whitespace({ direction = directions.BEFORE_CURSOR })
end, opts)
-- vim.keymap.set("", "3t", function()
--   hop.hint_lines_skip_whitespace({ direction = directions.AFTER_CURSOR, hint_offset = -1 })
-- end, opts)
-- vim.keymap.set("", "3T", function()
--   hop.hint_lines_skip_whitespace({ direction = directions.BEFORE_CURSOR, hint_offset = 1 })
-- end, opts)

vim.keymap.set("", "4f", function()
  hop.hint_vertical({ direction = directions.AFTER_CURSOR })
end, opts)
vim.keymap.set("", "4F", function()
  hop.hint_vertical({ direction = directions.BEFORE_CURSOR })
end, opts)
-- vim.keymap.set("", "4t", function()
--   hop.hint_vertical({ direction = directions.AFTER_CURSOR, hint_offset = -1 })
-- end, opts)
-- vim.keymap.set("", "4T", function()
--   hop.hint_vertical({ direction = directions.BEFORE_CURSOR, hint_offset = 1 })
-- end, opts)
